### ISSUE TITLE
Example not working: http://178.62.26.29:8080/api

### ISSUE THREAD

**Issue by rsubasic** [robtweed/qewd-conduit#1]
Hi Rob.  Tried the example and not working.  Probably I jumped the gun.  Page shows:
Cannot GET /api

**Comment by robtweed** [comment]
That's because, being just a REST back-end, the endpoint /api isn't defined.  See the realWorld API spec and you'll see the valid endpoints.  eg, if you want to try one of the unauthenticated GET endpoints, try /api/tags

**Comment by rsubasic** [comment]
Thanks Rob.  Sorry for the incomplete read.  Tested as suggested and works.  All the best.
